### ISSUE TITLE
Add Dummy Plugin and add all operational modes

### ISSUE THREAD

**Issue by sfehlandt** [IntegratedAlarmSystem-Group/ias-plugins#1]
Currently there is a dummy plugin in the integrations tools repo: https://github.com/IntegratedAlarmSystem-Group/integration-tools/blob/develop/demo/src/DummyPlugin.java

It should be moved here.

Also, all operational modes should be considered

**Comment by cristobal-vildosola** [comment]
Dummy plugin added, feature/dummy plugin already merged.
